"""
Numerical solvers for one-dimensional quantum wave-packet dynamics.

This module constructs the finite-difference Hamiltonian and evolves
a wave function under the time-dependent Schrödinger equation.
"""

import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import expm_multiply


def build_hamiltonian(x, V, hbar=1.0, mass=1.0):
    """
    Build the one-dimensional finite-difference Hamiltonian.

    Parameters
    ----------
    x : np.ndarray
        One-dimensional spatial grid.
    V : np.ndarray
        Potential-energy values on the grid.
    hbar : float, optional
        Reduced Planck constant. Default is 1.0.
    mass : float, optional
        Particle mass. Default is 1.0.

    Returns
    -------
    H : scipy.sparse matrix
        Sparse Hamiltonian matrix.

    Notes
    -----
    The Hamiltonian is

        H = -(hbar^2 / 2m) d^2/dx^2 + V(x)

    The second derivative is approximated using the central finite-difference rule.
    """

    dx = x[1] - x[0]
    n = len(x)

    kinetic_prefactor = -(hbar**2) / (2.0 * mass * dx**2)

    main_diagonal = -2.0 * np.ones(n)
    off_diagonal = np.ones(n - 1)

    second_derivative = diags(
        diagonals=[off_diagonal, main_diagonal, off_diagonal],
        offsets=[-1, 0, 1],
        format="csr",
    )

    kinetic = kinetic_prefactor * second_derivative
    potential = diags(V, offsets=0, format="csr")

    H = kinetic + potential

    return H


def evolve_state(psi0, H, times, hbar=1.0):
    """
    Evolve an initial wave function under a time-independent Hamiltonian.

    Parameters
    ----------
    psi0 : np.ndarray
        Initial complex-valued wave function.
    H : scipy.sparse matrix
        Hamiltonian matrix.
    times : np.ndarray
        Array of time values at which the state is evaluated.
    hbar : float, optional
        Reduced Planck constant. Default is 1.0.

    Returns
    -------
    states : np.ndarray
        Array of wave functions. states[j] gives psi(x, t_j).

    Notes
    -----
    The time evolution is generated by

        psi(t) = exp(-i H t / hbar) psi(0)

    The computation uses scipy.sparse.linalg.expm_multiply, which applies
    the matrix exponential to the state without explicitly constructing
    the dense exponential matrix.
    """

    generator = (-1j / hbar) * H

    states = expm_multiply(
        generator,
        psi0,
        start=times[0],
        stop=times[-1],
        num=len(times),
        endpoint=True,
    )

    return states